kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{.Values.volume.storageClassName}}
